# yamllint disable rule:line-length
# yamllint disable rule:braces
name: PR Approval

on:
  pull_request:

env:
  LINES: >-
    "Whatever you say!"
    "Isn't this exciting? I know I'm excited!"
    "I have a good feeling about this! It's going to be great!"
    "You really know how to make a robot happy! Seriously, you just made my day."
    "Good one!"
    "Wow, that's great!"
    "Absolutely, positively, without a doubt!"
    "Consider it done!"
    "I couldn't agree more!"
    "Fantastic choice!"
    "You're the boss! No doubt about it."
    "I'm all in! Let's do this!"
    "Brilliant idea! I'm on board."
    "Your wish is my command!"
    "I like your style! Let's roll with it."
    "I'm loving the enthusiasm! Count me in."
    "Rock on! I'm with you 100%."
    "Great call! You've got a knack for this."
    "You're a genius! I'm just here for the ride."
    "Absolutely positively affirmative!"
    "Bravo! That's the spirit."
    "Thumbs up! You're making all the right moves."
    "Genius move! You've got the Midas touch."
    "Couldn't have said it better myself!"
    "Absolutely, unequivocally, undeniably yes!"
    "Outstanding! Let's make it happen."
    "Cheers to that decision! You've got my approval."
    "Oh, this is gonna be wild! Count me in!"
    "That's a 10 out of 10 on the decision scale!"
    "You're the boss! I'm just here for the yuks."
    "I love it when you take charge! Let's make it happen."
    "Fantastic choice! I'm programmed to love your decisions."
    "Thumbs up! You're nailing this decision-making thing."
    "Absolutely positively, without a glitch!"
    "You're the brains, I'm the processor – let's do this!"
    "Approved with flying colors! You're on fire, friend!"

jobs:
  approve_pr:
    name: Automatic Approval
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner

    steps:
      - name: Approve PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          shuf -n 1 -e ${{ env.LINES }} |
          gh pr review ${{ github.event.pull_request.html_url }} --approve --body-file -
