# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: CI

on:
  pull_request: null
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
env:
  COMPOSER_ROOT_VERSION: '0.1.x-dev'

jobs:
  tests:
    name: Test with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: composer:v2

      - name: Validate composer.json
        run: |
          make composer-validate

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer remove --no-update --dev --no-interaction --no-progress \
            phan/phan phpstan/phpstan vimeo/psalm \
            infection/infection friendsofphp/php-cs-fixer
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: |
          ./vendor/bin/phpunit

  validate:
    name: Static Analysis and Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ast
          coverage: pcov
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

      - name: Validate composer.json
        run: |
          make composer-validate

      - name: Static Analysis
        run: |
          make ci-analyze --keep-going

      - name: Upload coverage report
        continue-on-error: false
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
        run: |
          ./vendor/bin/php-coveralls -v

  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2']
        php-cs-fixer-version: ['v3.35.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-cs-fixer:${{ matrix.php-cs-fixer-version }}

      - name: Restore PHP-CS-Fixer cache
        uses: actions/cache@v3
        with:
          path: .php_cs.cache
          key: php-cs-fixer
          restore-keys: php-cs-fixer

      - name: Run PHP-CS-Fixer ${{ matrix.php-cs-fixer-version }}
        run: |
          php-cs-fixer fix --diff --dry-run --verbose
